# Generated by Django 4.2.13 on 2024-06-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'abbreviation', 'address')},
        ),
    ]
